[package]
name = "io_uring_insecure_sockets_layer"
description.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
util.workspace = true

color-eyre.workspace = true

rustix-uring.workspace = true
