[package]
name = "io_uring_pest_control"
description.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
util.workspace = true

color-eyre.workspace = true

rustix-uring.workspace = true
