[package]
name = "may_mob_in_the_middle"
description.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
util.workspace = true

color-eyre.workspace = true

may.workspace = true
