[package]
name = "threaded_mob_in_the_middle"
description.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
util.workspace = true

color-eyre.workspace = true

socket2.workspace = true
tracing.workspace = true
