[package]
name = "threaded_smoke_test"
description.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
util.workspace = true

color-eyre.workspace = true
tracing.workspace = true

socket2.workspace = true
