[package]
name = "async_tokio_pest_control"
description.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
util.workspace = true

color-eyre.workspace = true
tracing.workspace = true

tokio.workspace = true
