[package]
name = "util"
authors.workspace = true
description.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
color-eyre.workspace = true
tracing.workspace = true
tracing-error.workspace = true
tracing-subscriber.workspace = true
