[package]
name = "async_ntex_smoke_test"
description.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
util.workspace = true

color-eyre.workspace = true
tracing.workspace = true

ntex-neon.workspace = true
ntex-net.workspace = true
