[package]
name = "epoll_pest_control"
description.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
util.workspace = true

color-eyre.workspace = true

polling.workspace = true
