[package]
name = "threaded_prime_time"
description.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
util.workspace = true

color-eyre.workspace = true

socket2.workspace = true
